### ISSUE TITLE
Todo list feature

### ISSUE THREAD

**Issue by mbasaglia** [mbasaglia/Melanobot#22]
Add a list to handle todo lists
* [ ] Create a new list identifier `Bot: todo newlist stuff` (Opt)
* [ ] Enable user lists `Bot: todo init` 
* [ ] Add new entries `Bot: todo (list) add something`
* [ ] Display entries `Bot: todo (list)`
* [ ] Remove entries `Bot: todo (list) rm #2|something`
* [ ] Automatic topic `Bot: todo topic Stuff to do: %`

**Comment by mbasaglia** [comment]
Moved to v2
