### ISSUE TITLE
misc todo

### ISSUE THREAD

**Issue by mbasaglia** [mbasaglia/Melanobot#3]
- [x] Simple multiple rcon example
- [x] Multicast irc -> rcon chat
- [x] rcon -> irc convert special characters
- [x] option to print scores inline
